name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: List directory
        run: ls -la

      - name: Build
        run: |
          xcodebuild -project ProcessReporter.xcodeproj \
            -scheme ProcessReporter \
            -configuration Release \
            -arch arm64 \
            -derivedDataPath build \
            CODE_SIGN_IDENTITY="-" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Create dmg
        run: |
          hdiutil create -fs HFS+ -volname "ProcessReporter" -srcfolder build/Build/Products/Release/ProcessReporter.app build/ProcessReporter-arm64.dmg

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/ProcessReporter-arm64.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
